CREATE DATABASE IF NOT EXISTS ZOMATO_DB;
USE ZOMATO_DB;
CREATE OR REPLACE SCHEMA ZOMATO_BRONZE_SCHEMA;
CREATE OR REPLACE SCHEMA ZOMATO_SILVER_SCHEMA;
CREATE OR REPLACE SCHEMA ZOMATO_GOLD_SCHEMA;
SHOW SCHEMAS;
