USE ZOMATO_DB.ZOMATO_BRONZE_SCHEMA;
CREATE STAGE IF NOT EXISTS ZOMATO_RAW_DATA DIRECTORY=(ENABLE = TRUE);
PUT file:///Users/chrysocolla/repos/zomato_data_pipeline/data/zomato_master_data.csv @ZOMATO_RAW_DATA AUTO_COMPRESS=TRUE;

LIST @ZOMATO_RAW_DATA;
