USE ZOMATO_DB.ZOMATO_GOLD_SCHEMA;

-- Total Revenue (GMV) : total order amount from delivered orders.
CREATE OR REPLACE SECURE VIEW GOLD_VW_TOTAL_REVENUE AS
SELECT ROUND(SUM(COALESCE(AMOUNT, 0)), 2) AS TOTAL_REVENUE
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER
WHERE UPPER(ORDER_STATUS) = 'DELIVERED'; 

-- Total Orders : count of all orders placed.
CREATE OR REPLACE SECURE VIEW GOLD_VW_TOTAL_ORDERS AS
SELECT COUNT(*) AS TOTAL_ORDERS
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER;

-- Average Order Value (AOV) : revenue ÷ number of orders.
CREATE OR REPLACE SECURE VIEW GOLD_VW_AVG_ORDER_VALUE AS
SELECT ROUND(AVG(COALESCE(AMOUNT, 0)), 2)  AS AVG_ORD_VAL
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER;
CREATE OR REPLACE SECURE VIEW GOLD_VW_AVG_DELIVERED_ORDER_VAL AS
SELECT ROUND(AVG(COALESCE(AMOUNT, 0)), 2)  AS AVG_DELIVERED_ORD_VAL
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER
WHERE UPPER(ORDER_STATUS) = 'DELIVERED'; 

-- Total Cancelled Order value.
CREATE OR REPLACE SECURE VIEW GOLD_VW_TOTAL_CANCELLED_ORDER_VALUE AS
SELECT ROUND(SUM(COALESCE(AMOUNT, 0)), 2)  AS TOTAL_CANCELLED_ORD_VAL
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER
WHERE UPPER(ORDER_STATUS) = 'CANCELLED';

-- New Customers per Month.
CREATE OR REPLACE SECURE VIEW GOLD_VW_NEW_CUSTOMERS_PER_MONTH AS
SELECT 
    TO_CHAR(SIGNUP_DATE, 'YYYY-MM') AS SIGNUP_MONTH,
    COUNT(DISTINCT CUST_ID) AS NEW_CUSTOMERS
FROM ZOMATO_SILVER_SCHEMA.DIM_CUSTOMER
GROUP BY TO_CHAR(SIGNUP_DATE, 'YYYY-MM')
ORDER BY SIGNUP_MONTH;


-- High Oder Frequency Customers : % of customers with more than 5 orders.
CREATE OR REPLACE SECURE VIEW GOLD_VW_PERCENT_HIGH_ORDER_FREQ_CUST AS
WITH ORDER_PER_CUST AS (
  SELECT CUST_ID, COUNT(*) AS n_orders
  FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER
  GROUP BY CUST_ID
)
SELECT ROUND(
         COUNT_IF(n_orders >= 5)
         / NULLIF(COUNT(*),0)::FLOAT
       ,2) * 100 AS PERCENT_HIGH_ORDER_FREQ_CUST
FROM ORDER_PER_CUST;


-- Order Status Distribution : DISTRIBUTION of Delivered, In Progress, Cancelled.
CREATE OR REPLACE SECURE VIEW GOLD_VW_ORDER_DISTRIBUTION_BY_STATUS AS
SELECT 'DELIVERED' AS order_status, 
       SUM(CASE WHEN UPPER(ORDER_STATUS) = 'DELIVERED' THEN 1 END) / COUNT(*) AS DISTRIBUTION
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER
UNION ALL
SELECT 'IN PROGRESS' AS order_status, 
       SUM(CASE WHEN UPPER(ORDER_STATUS) = 'IN PROGRESS' THEN 1 END) / COUNT(*) AS DISTRIBUTION
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER
UNION ALL
SELECT 'CANCELLED' AS order_status, 
       SUM(CASE WHEN UPPER(ORDER_STATUS) = 'CANCELLED' THEN 1 END) / COUNT(*) AS DISTRIBUTION
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER;

-- Payment Mode Mix : % of orders by UPI, Cash, Card.
CREATE OR REPLACE SECURE VIEW GOLD_VW_PAYMENT_MODE_DISTRIBUTION AS
SELECT 'UPI' AS MODE, 
       SUM(CASE WHEN UPPER(PAYMENT_MODE) = 'UPI' THEN 1 END) / COUNT(*) AS DISTRIBUTION
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER
UNION ALL
SELECT 'CASH' AS MODE, 
       SUM(CASE WHEN UPPER(PAYMENT_MODE) = 'CASH' THEN 1 END) / COUNT(*) AS DISTRIBUTION
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER
UNION ALL
SELECT 'CARD' AS MODE, 
       SUM(CASE WHEN UPPER(PAYMENT_MODE) = 'CARD' THEN 1 END) / COUNT(*) AS DISTRIBUTION
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER;

-- Top 10 Restaurants by Revenue : ranking of restaurants by total successful order amount.
CREATE OR REPLACE SECURE VIEW GOLD_VW_TOP_10_RESTAURANT_BY_REVENUE AS
SELECT O.REST_ID, DR.REST_NAME, ROUND(SUM(COALESCE(AMOUNT, 0)), 2) AS REVENUE
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER O
JOIN ZOMATO_SILVER_SCHEMA.DIM_RESTAURANT DR ON DR.REST_ID = O.REST_ID
WHERE UPPER(ORDER_STATUS) = 'DELIVERED'
GROUP BY O.REST_ID, DR.REST_NAME
ORDER BY REVENUE DESC 
LIMIT 10;

-- Cuisine DISTRIBUTION : % of total orders by cuisine type (e.g. Indian, Thai, Italian...).
CREATE OR REPLACE SECURE VIEW GOLD_VW_TOTAL_ORDER_BY_CUISINE AS
SELECT 
    DR.CUISINE, 
    COUNT(*) AS NUM_ORDERS
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER O
JOIN ZOMATO_SILVER_SCHEMA.DIM_RESTAURANT DR ON DR.REST_ID = O.REST_ID
GROUP BY DR.CUISINE
ORDER BY NUM_ORDERS DESC; 

-- Give order value by cuisine
CREATE OR REPLACE SECURE VIEW GOLD_VW_ORDER_VALUE_BY_CUISINE AS
SELECT 
    DR.CUISINE, 
    SUM(COALESCE(AMOUNT, 0)) AS TOTAL_REVENUE
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER O
JOIN ZOMATO_SILVER_SCHEMA.DIM_RESTAURANT DR ON DR.REST_ID = O.REST_ID
GROUP BY DR.CUISINE
ORDER BY TOTAL_REVENUE DESC; 

-- Cancel rate by delivery agent
CREATE OR REPLACE SECURE VIEW GOLD_VW_CANCEL_RATE_BY_DELIVERY_AGENT AS
SELECT 
    O.DEL_ID, 
    DD.DEL_NAME AS "DELIVERY AGENT", 
    ROUND(COUNT(CASE WHEN UPPER(O.ORDER_STATUS)='CANCELLED' THEN 1 END)/COUNT(*), 2) AS CANCEL_RATE
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER O
JOIN ZOMATO_SILVER_SCHEMA.DIM_DELIVERY DD ON DD.DEL_ID = O.DEL_ID
GROUP BY O.DEL_ID, DD.DEL_NAME
ORDER BY CANCEL_RATE; 

-- Find Customer lifetime value
CREATE OR REPLACE SECURE VIEW GOLD_VW_CUSTOMER_LIFE_TIME_VALUE AS
SELECT 
    O.CUST_ID, 
    DC.CUST_NAME, 
    SUM(COALESCE(AMOUNT, 0)) AS TOTAL_SPENT
FROM ZOMATO_SILVER_SCHEMA.FACT_ORDER O
JOIN ZOMATO_SILVER_SCHEMA.DIM_CUSTOMER DC ON DC.CUST_ID = O.CUST_ID
WHERE UPPER(ORDER_STATUS)='DELIVERED'
GROUP BY O.CUST_ID, DC.CUST_NAME
ORDER BY TOTAL_SPENT DESC; 