USE ZOMATO_DB.ZOMATO_SILVER_SCHEMA;

-------------------------------------------------------------------
--                     DIM CUSTOMER 
-------------------------------------------------------------------

CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUST_ID     INT AUTOINCREMENT PRIMARY KEY,
  CUST_NAME   STRING,
  CUST_EMAIL  STRING,
  CUST_PHONE  STRING,
  CUST_CITY   STRING,
  SIGNUP_DATE DATE
);

INSERT INTO DIM_CUSTOMER(CUST_NAME, CUST_EMAIL, CUST_PHONE, CUST_CITY, SIGNUP_DATE) 
SELECT 
  DISTINCT CUST_NAME, CUST_EMAIL, CUST_PHONE, CUST_CITY, SIGNUP_DATE
FROM ZOMATO_BRONZE_SCHEMA.BRONZE_ZOMATO_BASE;

SELECT CUST_NAME, COUNT(*) AS cnt
FROM DIM_CUSTOMER
GROUP BY CUST_NAME
HAVING COUNT(*) > 1
ORDER BY cnt DESC; 

SELECT * FROM DIM_CUSTOMER WHERE CUST_NAME = 'Sarah Wagner';

DELETE FROM DIM_CUSTOMER 
WHERE CUST_ID = 12; 
SELECT CUST_NAME, COUNT(*) AS cnt
FROM DIM_CUSTOMER
GROUP BY CUST_NAME
HAVING COUNT(*) > 1
ORDER BY cnt DESC; 

-------------------------------------------------------------------
--                     DIM RESTAURANT  
-------------------------------------------------------------------

CREATE OR REPLACE TABLE DIM_RESTAURANT (
  REST_ID     INT AUTOINCREMENT PRIMARY KEY,
  REST_NAME   STRING,
  REST_CITY   STRING,
  CUISINE     STRING
);
INSERT INTO DIM_RESTAURANT(REST_NAME, REST_CITY, CUISINE) 
SELECT 
  DISTINCT NAME_REST, CITY_REST, CUISINE
FROM ZOMATO_BRONZE_SCHEMA.BRONZE_ZOMATO_BASE;

SELECT REST_NAME, COUNT(*) AS cnt
FROM DIM_RESTAURANT
GROUP BY REST_NAME
HAVING COUNT(*) > 1
ORDER BY cnt DESC;

-------------------------------------------------------------------
--                     DIM DELIVERY TABLE  
-------------------------------------------------------------------
CREATE OR REPLACE TABLE DIM_DELIVERY (
  DEL_ID        INT AUTOINCREMENT PRIMARY KEY,
  DEL_NAME      STRING,
  VEHICLE_TYPE  STRING,
  DEL_CITY      STRING,
  DEL_PHONE     STRING
);

INSERT INTO DIM_DELIVERY(DEL_NAME, VEHICLE_TYPE, DEL_CITY, DEL_PHONE)
SELECT 
  DISTINCT NAME_DEL, VEHICLE_TYPE, CITY_DEL, PHONE_DEL
FROM ZOMATO_BRONZE_SCHEMA.BRONZE_ZOMATO_BASE;

SELECT DEL_NAME, COUNT(*) AS cnt
FROM DIM_DELIVERY
GROUP BY DEL_NAME
HAVING COUNT(*) > 1
ORDER BY cnt DESC;

-------------------------------------------------------------------
--                     FACT TABLE  
-------------------------------------------------------------------
CREATE OR REPLACE TABLE FACT_ORDER (
  ORDER_ID      INT AUTOINCREMENT PRIMARY KEY,
  CUST_ID       INT, 
  REST_ID       INT, 
  DEL_ID        INT, 
  AMOUNT        DECIMAL(10, 2),
  PAYMENT_MODE  STRING,
  ORDER_STATUS  STRING, 
  FOREIGN KEY (CUST_ID) REFERENCES DIM_CUSTOMER(CUST_ID),
  FOREIGN KEY (REST_ID) REFERENCES DIM_RESTAURANT(REST_ID),
  FOREIGN KEY (DEL_ID) REFERENCES DIM_DELIVERY(DEL_ID)
);

INSERT INTO FACT_ORDER(CUST_ID, REST_ID, DEL_ID, AMOUNT, PAYMENT_MODE, ORDER_STATUS)
SELECT 
  CUST_ID,
  REST_ID,
  DEL_ID,
  BT.AMOUNT, 
  BT.PAYMENT_MODE, 
  BT.ORDER_STATUS
FROM ZOMATO_BRONZE_SCHEMA.BRONZE_ZOMATO_BASE AS BT
JOIN DIM_CUSTOMER   DC ON DC.CUST_NAME = BT.CUST_NAME AND DC.CUST_EMAIL = BT.CUST_EMAIL
JOIN DIM_DELIVERY   DD ON DD.DEL_NAME  = BT.NAME_DEL AND DD.DEL_PHONE = BT.PHONE_DEL
JOIN DIM_RESTAURANT DR ON DR.REST_NAME = BT.NAME_REST AND DR.REST_CITY = BT.CITY_REST;

SELECT * FROM FACT_ORDER;

-- ROW COUNT CHECK : BASE, FACT 
SELECT
  (SELECT COUNT(*) FROM ZOMATO_BRONZE_SCHEMA.BRONZE_ZOMATO_BASE) AS bronze_rows,
  (SELECT COUNT(*) FROM FACT_ORDER) AS fact_rows;